name: NBA Hub Updater
on:
  schedule:
    - cron: '0 * * * *' # Roda automaticamente de 1 em 1 hora
  workflow_dispatch: # Habilita o botão manual que você estava procurando

jobs:
  atualizar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalar bibliotecas
        run: pip install pandas supabase lxml html5lib beautifulsoup4
      - name: Executar Script
              env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        NBA_API_KEY: ${{ secrets.NBA_API_KEY }} # Adicione esta linha
